### ISSUE TITLE
9월 13일 활동 내용 공유 이슈입니다.

### ISSUE THREAD

**Issue by ttfcl** [codestates-seb/seb39_main_003#2]
오늘 하루 활동 내용 공유하는 공간입니다.
14일 오전 9시 종합회의 전까지 작성해주세요.

**Comment by jaekwan278** [comment]
1. Git Flow
2. 멘토 회의
3. 배포 EC2, RDS

**Comment by mirea70** [comment]
테이블 설계 ( done)
기능 구현 및 테이블 관련 추가논의 필요(디스코드에 남김)

**Comment by jgb1123** [comment]
1. 테이블 설계 ( done)
2. 기능 구현 및 테이블 관련 추가논의 필요(디스코드에 남김)

**Comment by guswns3198** [comment]
Nav바에 있는 "쇼핑" 탭 페이지 화면 구현

1. 캐러셀 구현 (이벤트 이미지 슬라이드)
2. 사료, 간식, 용품 등 강아지 관련 상품 카테고리 분류
3. 이 달의 인기상품 목록 표시

**Comment by nomga** [comment]
1. 동물병원 커뮤니티 페이지 작성

**Comment by ttfcl** [comment]
1. 공지사항 페이지 설계
2. 공지사항 목록 더미데이터로 렌더링
3. dev브랜치를 파이어베이스로 배포
